#!/usr/bin/env bash

case "$1" in
    lock)
        $HOME/bin/i3lock-wrapper
        ;;
    logout)
        i3-msg exit
        ;;
    reboot)
        sudo shutdown -r now
        ;;
    shutdown)
        sudo shutdown -h now
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
        exit 2
esac

exit 0
