#!/usr/bin/env bash

case "$1" in
    lock)
        $HOME/.i3/i3lock-wrapper
        ;;
    sleep)
        $HOME/.i3/i3lock-wrapper &
        sudo /usr/sbin/pm-suspend
        ;;
    logout)
        i3-msg exit
        ;;
    reboot)
        sudo /sbin/shutdown -r now
        ;;
    shutdown)
        sudo /sbin/shutdown -h now
        ;;
    *)
        echo "Usage: $0 [lock|sleep|logout|reboot|shutdown]"
        exit 2
esac

exit 0
