#!/usr/bin/env bash

case "$1" in
    lock)
        $HOME/.i3/i3lock-wrapper
        ;;
    logout)
        i3-msg exit
        ;;
    sleep)
        $HOME/.i3/i3lock-wrapper &
        sleep 0.5
        sudo systemctl suspend-then-hibernate
        ;;
    hibernate)
        $HOME/.i3/i3lock-wrapper &
        sleep 0.5
        sudo systemctl hibernate
        ;;
    restart)
        sudo systemctl reboot
        ;;
    shutdown)
        sudo systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|sleep|hibernate|restart|shutdown]"
        exit 2
esac

exit 0
